apiVersion: v1
kind: Service
metadata:
  name: welcome-app-service
spec:
  selector:
    app: welcome-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
