# -*- coding: utf-8 -*-
"""Text_lstm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhJ380YSAforfOenRDbJsg3F7cdoNiyE
"""

# Install TensorFlow if needed
# !pip install tensorflow

import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# 1. Load IMDb dataset
vocab_size = 10000   # top 10k words
maxlen = 200         # max review length

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)

# Pad sequences so all have same length
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test = pad_sequences(x_test, maxlen=maxlen)

# 2. Build LSTM model
embedding_dim = 32
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=maxlen),
    LSTM(64),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 3. Train model
epochs = 3
batch_size = 64
history = model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size,
                    validation_split=0.1, verbose=1)

# 4. Evaluate on test set
loss, accuracy = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

